CREATE DATABASE DATA_ANALYTICS_PROJECT;

USE DATA_ANALYTICS_PROJECT;

-- APPENDING THE DATASET FOR ALL COUNTRIES AND PUTTING INTO ONE TABLE
CREATE TABLE SOCCER_EVENT_DB
SELECT *
FROM SOCCER_DB_ENGLAND2011
UNION ALL
SELECT *
FROM SOCCER_DB_ENGLAND2012
UNION ALL
SELECT *
FROM SOCCER_DB_ENGLAND2013
UNION ALL
SELECT *
FROM SOCCER_DB_ENGLAND2014
UNION ALL
SELECT *
FROM SOCCER_DB_ENGLAND2015
UNION ALL
SELECT *
FROM SOCCER_DB_FRANCE2011
UNION ALL
SELECT *
FROM SOCCER_DB_FRANCE2012
UNION ALL
SELECT *
FROM SOCCER_DB_FRANCE2013
UNION ALL
SELECT *
FROM SOCCER_DB_FRANCE2014
UNION ALL
SELECT *
FROM SOCCER_DB_FRANCE2015
UNION ALL
SELECT *
FROM SOCCER_DB_GERMANY2011
UNION ALL
SELECT *
FROM SOCCER_DB_GERMANY2012
UNION ALL
SELECT *
FROM SOCCER_DB_GERMANY2013
UNION ALL
SELECT *
FROM SOCCER_DB_GERMANY2014
UNION ALL
SELECT *
FROM SOCCER_DB_GERMANY2015
UNION ALL
SELECT *
FROM SOCCER_DB_ITALY2011
UNION ALL
SELECT *
FROM SOCCER_DB_ITALY2012
UNION ALL
SELECT *
FROM SOCCER_DB_ITALY2013
UNION ALL
SELECT *
FROM SOCCER_DB_ITALY2014
UNION ALL
SELECT *
FROM SOCCER_DB_ITALY2015
UNION ALL
SELECT *
FROM SOCCER_DB_SPAIN2011
UNION ALL
SELECT *
FROM SOCCER_DB_SPAIN2012
UNION ALL
SELECT *
FROM SOCCER_DB_SPAIN2013
UNION ALL
SELECT *
FROM SOCCER_DB_SPAIN2014
UNION ALL
SELECT *
FROM SOCCER_DB_SPAIN2015;
-- 168,447 RECORDS RETURNED

--REMOVING THE EVENTS WHERE THE TIME WAS NOT RECORDED IN THE DATA
CREATE TABLE PROJECT_TIME_CORRECTED
SELECT COUNTRY, 
	MATCH_ID, 
	HOME_TEAM, 
	AWAY_TEAM, 
	MATCH_DATE, 
	STADIUM, 
	EVENT, 
	CONVERT(TIME, UNSIGNED) AS TIME
FROM SOCCER_EVENT_DB
WHERE TIME != 'NONE';
-- 157,230 RECORDS RETURNED

--CONVERTING EACH EVENT TO A COLUMN AND STORING THE CUMULATIVE FOR EACH OF THEM AT 5 MIN INTERVAL
--FOR EX - YELLOW CARDS WILL HAVE 18 COLUMNS, ONE FOR EACH 5 MINUTE GAP AND SO ON FOR EACH EVENT
--IT'S A 1600 LINE CODE!! BUT WE DID NOT TYPE IT. WE USED A FORMULA IN EXCEL AND THE JOB WAS DONE IN BARELY 2 MINS
CREATE TABLE SOCCER_DB_ADS
SELECT COUNTRY,
	MATCH_ID,
	HOME_TEAM,
	AWAY_TEAM,
	MATCH_DATE,
	STADIUM,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_YELLOWCARDS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_YELLOWCARDS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBOUTS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_SUBOUTS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_SUBINS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_SUBINS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_REDCARDS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_REDCARDS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_PENALTYGOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_PENALTYGOALS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_OWNGOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_OWNGOALS_0,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_85,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_80,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_75,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_70,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_65,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_60,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_55,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_50,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_45,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_40,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_35,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_30,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_25,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_20,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_15,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_10,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_5,
	SUM(CASE 
			WHEN EVENT = 'HOME_GOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS HOME_GOALS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_YELLOWCARDS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_YELLOWCARDS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBOUTS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_SUBOUTS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_SUBINS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_SUBINS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_REDCARDS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_REDCARDS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_PENALTYGOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_PENALTYGOALS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_OWNGOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_OWNGOALS_0,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_FT,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 85
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_85,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 80
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_80,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 75
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_75,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 70
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_70,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 65
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_65,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 60
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_60,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 55
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_55,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 50
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_50,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 45
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_45,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 40
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_40,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 35
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_35,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 30
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_30,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 25
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_25,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 20
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_20,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 15
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_15,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 10
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_10,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 5
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_5,
	SUM(CASE 
			WHEN EVENT = 'AWAY_GOALS'
				AND TIME <= 0
				THEN 1
			ELSE 0
			END) AS AWAY_GOALS_0
FROM PROJECT_TIME_CORRECTED
GROUP BY COUNTRY,
	MATCH_ID,
	HOME_TEAM,
	AWAY_TEAM,
	MATCH_DATE,
	STADIUM;
-- 9,123 RECORDS RETURNED
	
-- CONVERTING THE GOALS SCORED BY EACH TEAM AT A TIME INTERVAL TO THE GOAL DIFFERENCE
CREATE TABLE SOCCER_DB_GOAL_DIFF
SELECT *,
	(HOME_PENALTYGOALS_FT + AWAY_OWNGOALS_FT + HOME_GOALS_FT) - (AWAY_PENALTYGOALS_FT + HOME_OWNGOALS_FT + AWAY_GOALS_FT) AS GD_FT,
	(HOME_PENALTYGOALS_85 + AWAY_OWNGOALS_85 + HOME_GOALS_85) - (AWAY_PENALTYGOALS_85 + HOME_OWNGOALS_85 + AWAY_GOALS_85) AS GD_85,
	(HOME_PENALTYGOALS_80 + AWAY_OWNGOALS_80 + HOME_GOALS_80) - (AWAY_PENALTYGOALS_80 + HOME_OWNGOALS_80 + AWAY_GOALS_80) AS GD_80,
	(HOME_PENALTYGOALS_75 + AWAY_OWNGOALS_75 + HOME_GOALS_75) - (AWAY_PENALTYGOALS_75 + HOME_OWNGOALS_75 + AWAY_GOALS_75) AS GD_75,
	(HOME_PENALTYGOALS_70 + AWAY_OWNGOALS_70 + HOME_GOALS_70) - (AWAY_PENALTYGOALS_70 + HOME_OWNGOALS_70 + AWAY_GOALS_70) AS GD_70,
	(HOME_PENALTYGOALS_65 + AWAY_OWNGOALS_65 + HOME_GOALS_65) - (AWAY_PENALTYGOALS_65 + HOME_OWNGOALS_65 + AWAY_GOALS_65) AS GD_65,
	(HOME_PENALTYGOALS_60 + AWAY_OWNGOALS_60 + HOME_GOALS_60) - (AWAY_PENALTYGOALS_60 + HOME_OWNGOALS_60 + AWAY_GOALS_60) AS GD_60,
	(HOME_PENALTYGOALS_55 + AWAY_OWNGOALS_55 + HOME_GOALS_55) - (AWAY_PENALTYGOALS_55 + HOME_OWNGOALS_55 + AWAY_GOALS_55) AS GD_55,
	(HOME_PENALTYGOALS_50 + AWAY_OWNGOALS_50 + HOME_GOALS_50) - (AWAY_PENALTYGOALS_50 + HOME_OWNGOALS_50 + AWAY_GOALS_50) AS GD_50,
	(HOME_PENALTYGOALS_45 + AWAY_OWNGOALS_45 + HOME_GOALS_45) - (AWAY_PENALTYGOALS_45 + HOME_OWNGOALS_45 + AWAY_GOALS_45) AS GD_45,
	(HOME_PENALTYGOALS_40 + AWAY_OWNGOALS_40 + HOME_GOALS_40) - (AWAY_PENALTYGOALS_40 + HOME_OWNGOALS_40 + AWAY_GOALS_40) AS GD_40,
	(HOME_PENALTYGOALS_35 + AWAY_OWNGOALS_35 + HOME_GOALS_35) - (AWAY_PENALTYGOALS_35 + HOME_OWNGOALS_35 + AWAY_GOALS_35) AS GD_35,
	(HOME_PENALTYGOALS_30 + AWAY_OWNGOALS_30 + HOME_GOALS_30) - (AWAY_PENALTYGOALS_30 + HOME_OWNGOALS_30 + AWAY_GOALS_30) AS GD_30,
	(HOME_PENALTYGOALS_25 + AWAY_OWNGOALS_25 + HOME_GOALS_25) - (AWAY_PENALTYGOALS_25 + HOME_OWNGOALS_25 + AWAY_GOALS_25) AS GD_25,
	(HOME_PENALTYGOALS_20 + AWAY_OWNGOALS_20 + HOME_GOALS_20) - (AWAY_PENALTYGOALS_20 + HOME_OWNGOALS_20 + AWAY_GOALS_20) AS GD_20,
	(HOME_PENALTYGOALS_15 + AWAY_OWNGOALS_15 + HOME_GOALS_15) - (AWAY_PENALTYGOALS_15 + HOME_OWNGOALS_15 + AWAY_GOALS_15) AS GD_15,
	(HOME_PENALTYGOALS_10 + AWAY_OWNGOALS_10 + HOME_GOALS_10) - (AWAY_PENALTYGOALS_10 + HOME_OWNGOALS_10 + AWAY_GOALS_10) AS GD_10,
	(HOME_PENALTYGOALS_5 + AWAY_OWNGOALS_5 + HOME_GOALS_5) - (AWAY_PENALTYGOALS_5 + HOME_OWNGOALS_5 + AWAY_GOALS_5) AS GD_5,
	(HOME_PENALTYGOALS_0 + AWAY_OWNGOALS_0 + HOME_GOALS_0) - (AWAY_PENALTYGOALS_0 + HOME_OWNGOALS_0 + AWAY_GOALS_0) AS GD_0
FROM SOCCER_DB_ADS;
-- 9,123 RECORDS RETURNED

-- CREATING AN OUTCOME COLUMN WHERE IT CHANGES THE OUTCOME FO THE GAME TO LEVELS FOR MACHINE LEARNING PURPOSES
CREATE TABLE SOCCER_DB_OUTCOME
SELECT *,
	(
		CASE 
			WHEN GD_FT > 0
				THEN 1
			WHEN GD_FT = 0
				THEN 2
			WHEN GD_FT < 0
				THEN 0
			END
		) OUTCOME
FROM SOCCER_DB_GOAL_DIFF;
-- 9,123 RECORDS RETURNED

-- CREATING THE PERFORMANCE SCORE FOR THE HOME TEAM
-- THIS IS BASED ON THE TEAM'S RECENT PERFORMANCE IN 2016
CREATE TABLE SOCCER_DB_HOME_TEAM_SCORE
SELECT HOME_TEAM,
	AVG(GD_FT) AS HOME_SCORE_GD,
	(
		SUM(CASE 
				WHEN OUTCOME = 1
					THEN 1
				ELSE 0
				END) * 1.0
		) / COUNT(*) AS HOME_PERCENT_WIN,
	(
		SUM(CASE 
				WHEN OUTCOME = 1
					THEN 3
				WHEN OUTCOME = 2
					THEN 1
				ELSE 0
				END) * 1.0
		) / (COUNT(*) * 3.0) AS HOME_PERCENT_POINTS
FROM (
	SELECT *
	FROM SOCCER_DB_OUTCOME
	WHERE SUBSTR(MATCH_DATE, 7, 4) >= "2016"
	) A
GROUP BY HOME_TEAM;
-- 98 RECORDS

-- CREATING THE PERFORMANCE SCORE FOR THE AWAY TEAM
CREATE TABLE SOCCER_DB_AWAY_TEAM_SCORE
SELECT AWAY_TEAM,
	AVG(GD_FT) AS AWAY_SCORE_GD,
	(
		SUM(CASE 
				WHEN OUTCOME = 0
					THEN 1
				ELSE 0
				END) * 1.0
		) / COUNT(*) AS AWAY_PERCENT_WIN,
	(
		SUM(CASE 
				WHEN OUTCOME = 0
					THEN 3
				WHEN OUTCOME = 2
					THEN 1
				ELSE 0
				END) * 1.0
		) / (COUNT(*) * 3.0) AS AWAY_PERCENT_POINTS
FROM (
	SELECT *
	FROM SOCCER_DB_OUTCOME
	WHERE SUBSTR(MATCH_DATE, 7, 4) >= "2016"
	) A
GROUP BY AWAY_TEAM;
-- 98 RECORDS RETURNED

-- JOINING THE PERFORMANCE SCORE TO THE ORIGINAL TABLE
CREATE TABLE SOCCER_DB_SCORE
SELECT C.*,
	D.AWAY_SCORE_GD,
	D.AWAY_PERCENT_WIN,
	D.AWAY_PERCENT_POINTS
FROM (
	SELECT A.*,
		B.HOME_SCORE_GD,
		B.HOME_PERCENT_WIN,
		B.HOME_PERCENT_POINTS
	FROM SOCCER_DB_OUTCOME A
	LEFT JOIN SOCCER_DB_HOME_TEAM_SCORE B ON A.HOME_TEAM = B.HOME_TEAM
	) C
LEFT JOIN SOCCER_DB_AWAY_TEAM_SCORE D ON C.AWAY_TEAM = D.AWAY_TEAM;
-- 9,123 RECORDS RETURNED

-- FOR TEAMS WHICH HAVE NOT PLAYED A GAME IN 2016, THE SCORE WILL BE A NULL
-- CALCULATING THE DIFFERENCE IN THE SCORE OF THE HOME TEAM AND AWAY TEAM
CREATE TABLE SOCCER_DB_SCORE_DIFF
SELECT *,
	(IFNULL(HOME_SCORE_GD, 0) - IFNULL(AWAY_SCORE_GD, 0)) AS SCORE_DIFF,
	(IFNULL(HOME_PERCENT_WIN, 0) - IFNULL(AWAY_PERCENT_WIN, 0)) AS PERCENT_WIN_DIFF,
	(IFNULL(HOME_PERCENT_POINTS, 0) - IFNULL(AWAY_PERCENT_POINTS, 0)) AS PERCENT_POINTS_DIFF
FROM SOCCER_DB_SCORE;
-- 9,123 RECORDS RETURNED